-- CreateEnum
CREATE TYPE "public"."KichCo" AS ENUM ('S', 'M', 'L', 'XL', 'XXL');

-- CreateEnum
CREATE TYPE "public"."MauSac" AS ENUM ('Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Indigo', 'Violet', 'Black', 'White', 'Gray', 'Brown', 'Pink');

-- CreateEnum
CREATE TYPE "public"."TrangThai" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "public"."TrangThaiDonHang" AS ENUM ('DANG_XU_LY', 'DANG_GIAO_HANG', 'HOAN_TAT', 'HUY');

-- CreateEnum
CREATE TYPE "public"."TrangThaiSP" AS ENUM ('CON_HANG', 'HET_HANG', 'TAM_NGUNG');

-- CreateEnum
CREATE TYPE "public"."LoaiDanhMuc" AS ENUM ('NAM', 'NU', 'PHU_KIEN');

-- CreateEnum
CREATE TYPE "public"."TrangThaiPhieuNhapHang" AS ENUM ('DANG_CHO', 'NCC_XACNHAN', 'NV_XACNHAN', 'TU_CHOI');

-- CreateEnum
CREATE TYPE "public"."VaiTro" AS ENUM ('KH', 'NCC', 'QLDN', 'NVVH', 'NVCSKH', 'ADMIN');

-- CreateTable
CREATE TABLE "public"."CHITIETGIOHANG" (
    "MaCTGH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SoLuong" INTEGER NOT NULL DEFAULT 0,
    "MaGH" TEXT NOT NULL,
    "MaCTSP" TEXT NOT NULL,

    CONSTRAINT "CHITIETGIOHANG_pkey" PRIMARY KEY ("MaCTGH")
);

-- CreateTable
CREATE TABLE "public"."CHITIETSANPHAM" (
    "MaCTSP" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "KichCo" "public"."KichCo" NOT NULL,
    "MaSP" TEXT NOT NULL,
    "SoLuong" INTEGER NOT NULL DEFAULT 0,
    "TrangThaiSP" "public"."TrangThaiSP" NOT NULL DEFAULT 'CON_HANG',

    CONSTRAINT "CHITIETSANPHAM_pkey" PRIMARY KEY ("MaCTSP")
);

-- CreateTable
CREATE TABLE "public"."DANHMUC" (
    "MaDM" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TenDM" TEXT NOT NULL,
    "TrangThai" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "LoaiDanhMuc" "public"."LoaiDanhMuc" NOT NULL,

    CONSTRAINT "DANHMUC_pkey" PRIMARY KEY ("MaDM")
);

-- CreateTable
CREATE TABLE "public"."DONHANG" (
    "MaDH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SoLuong" INTEGER NOT NULL DEFAULT 0,
    "TongTien" INTEGER,
    "MaVoucher" TEXT,
    "MaCTSP" TEXT NOT NULL,
    "MaSK" TEXT,
    "MaTK_KH" TEXT,

    CONSTRAINT "DONHANG_pkey" PRIMARY KEY ("MaDH")
);

-- CreateTable
CREATE TABLE "public"."GIOHANG" (
    "MaGH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MaTKKH" TEXT,

    CONSTRAINT "GIOHANG_pkey" PRIMARY KEY ("MaGH")
);

-- CreateTable
CREATE TABLE "public"."NHACUNGCAP" (
    "MaNCC" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Email" TEXT,
    "DienThoai" TEXT,
    "DiaChi" TEXT,
    "TenNCC" TEXT NOT NULL,

    CONSTRAINT "NHACUNGCAP_pkey" PRIMARY KEY ("MaNCC")
);

-- CreateTable
CREATE TABLE "public"."PHANHOI" (
    "MaPH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "NoiDung" TEXT NOT NULL,
    "MaTKKH" TEXT NOT NULL,
    "MaSP" TEXT NOT NULL,
    "SoSao" INTEGER NOT NULL,
    "BinhLuan" TEXT,

    CONSTRAINT "PHANHOI_pkey" PRIMARY KEY ("MaPH")
);

-- CreateTable
CREATE TABLE "public"."SANPHAM" (
    "MaSP" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MoTa" TEXT,
    "TenSP" TEXT NOT NULL,
    "HinhAnh" TEXT[],
    "GiaBan" INTEGER NOT NULL,
    "GiaMua" INTEGER NOT NULL,
    "TrangThai" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "MaDM" TEXT NOT NULL,
    "MauSac" "public"."MauSac" NOT NULL,

    CONSTRAINT "SANPHAM_pkey" PRIMARY KEY ("MaSP")
);

-- CreateTable
CREATE TABLE "public"."SUKIENUUDAI" (
    "MaSK" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "NgayKT" TIMESTAMP(3) NOT NULL,
    "TenSK" TEXT NOT NULL,
    "NgayPH" TIMESTAMP(3) NOT NULL,
    "PhanTramGiam" INTEGER NOT NULL,
    "TrangThai" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "MoTa" TEXT,

    CONSTRAINT "SUKIENUUDAI_pkey" PRIMARY KEY ("MaSK")
);

-- CreateTable
CREATE TABLE "public"."TAIKHOAN" (
    "MaTK" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Username" TEXT,
    "MatKhau" TEXT,
    "Status" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "Avatar" TEXT,
    "VAITRO" "public"."VaiTro" NOT NULL,

    CONSTRAINT "TAIKHOAN_pkey" PRIMARY KEY ("MaTK")
);

-- CreateTable
CREATE TABLE "public"."TINHTRANGDONHANG" (
    "MaTTDH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TrangThai" "public"."TrangThaiDonHang" NOT NULL DEFAULT 'DANG_XU_LY',
    "MaDH" TEXT,

    CONSTRAINT "TINHTRANGDONHANG_pkey" PRIMARY KEY ("MaTTDH")
);

-- CreateTable
CREATE TABLE "public"."VOUCHER" (
    "MaVoucher" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TenVoucher" TEXT NOT NULL,
    "SoTien" INTEGER NOT NULL DEFAULT 0,
    "FreeShip" BOOLEAN NOT NULL DEFAULT false,
    "NgayBatDau" TIMESTAMP(3) NOT NULL,
    "NgayKetThuc" TIMESTAMP(3) NOT NULL,
    "Dieukien" INTEGER NOT NULL DEFAULT 0,
    "TrangThai" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "MoTa" TEXT,

    CONSTRAINT "VOUCHER_pkey" PRIMARY KEY ("MaVoucher")
);

-- CreateTable
CREATE TABLE "public"."VOUCHER_KHACHHANG" (
    "MaVCKH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TrangThai" "public"."TrangThai" NOT NULL DEFAULT 'ACTIVE',
    "MaTKKH" TEXT NOT NULL,
    "MaVoucher" TEXT NOT NULL,

    CONSTRAINT "VOUCHER_KHACHHANG_pkey" PRIMARY KEY ("MaVCKH")
);

-- CreateTable
CREATE TABLE "public"."PHIEUNHAPHANG" (
    "MaPNNH" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SoLuong" INTEGER NOT NULL,
    "MaCTSP" TEXT NOT NULL,
    "MaNCC" TEXT NOT NULL,
    "TrangThai" "public"."TrangThaiPhieuNhapHang" NOT NULL,
    "MaTKNVQL" TEXT,
    "MaTKNVXN" TEXT,
    "NoiDung" TEXT NOT NULL,

    CONSTRAINT "PHIEUNHAPHANG_pkey" PRIMARY KEY ("MaPNNH")
);

-- CreateIndex
CREATE UNIQUE INDEX "TAIKHOAN_Username_key" ON "public"."TAIKHOAN"("Username");

-- AddForeignKey
ALTER TABLE "public"."CHITIETGIOHANG" ADD CONSTRAINT "CHITIETGIOHANG_MaGH_fkey" FOREIGN KEY ("MaGH") REFERENCES "public"."GIOHANG"("MaGH") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."CHITIETGIOHANG" ADD CONSTRAINT "CHITIETGIOHANG_MaCTSP_fkey" FOREIGN KEY ("MaCTSP") REFERENCES "public"."CHITIETSANPHAM"("MaCTSP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."CHITIETSANPHAM" ADD CONSTRAINT "CHITIETSANPHAM_MaSP_fkey" FOREIGN KEY ("MaSP") REFERENCES "public"."SANPHAM"("MaSP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."DONHANG" ADD CONSTRAINT "DONHANG_MaCTSP_fkey" FOREIGN KEY ("MaCTSP") REFERENCES "public"."CHITIETSANPHAM"("MaCTSP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."DONHANG" ADD CONSTRAINT "DONHANG_MaTK_KH_fkey" FOREIGN KEY ("MaTK_KH") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."DONHANG" ADD CONSTRAINT "DONHANG_MaSK_fkey" FOREIGN KEY ("MaSK") REFERENCES "public"."SUKIENUUDAI"("MaSK") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."DONHANG" ADD CONSTRAINT "DONHANG_MaVoucher_fkey" FOREIGN KEY ("MaVoucher") REFERENCES "public"."VOUCHER"("MaVoucher") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."GIOHANG" ADD CONSTRAINT "GIOHANG_MaTKKH_fkey" FOREIGN KEY ("MaTKKH") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHANHOI" ADD CONSTRAINT "PHANHOI_MaTKKH_fkey" FOREIGN KEY ("MaTKKH") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHANHOI" ADD CONSTRAINT "PHANHOI_MaSP_fkey" FOREIGN KEY ("MaSP") REFERENCES "public"."SANPHAM"("MaSP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."SANPHAM" ADD CONSTRAINT "SANPHAM_MaDM_fkey" FOREIGN KEY ("MaDM") REFERENCES "public"."DANHMUC"("MaDM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TINHTRANGDONHANG" ADD CONSTRAINT "TINHTRANGDONHANG_MaDH_fkey" FOREIGN KEY ("MaDH") REFERENCES "public"."DONHANG"("MaDH") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."VOUCHER_KHACHHANG" ADD CONSTRAINT "VOUCHER_KHACHHANG_MaTKKH_fkey" FOREIGN KEY ("MaTKKH") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."VOUCHER_KHACHHANG" ADD CONSTRAINT "VOUCHER_KHACHHANG_MaVoucher_fkey" FOREIGN KEY ("MaVoucher") REFERENCES "public"."VOUCHER"("MaVoucher") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHIEUNHAPHANG" ADD CONSTRAINT "PHIEUNHAPHANG_MaCTSP_fkey" FOREIGN KEY ("MaCTSP") REFERENCES "public"."CHITIETSANPHAM"("MaCTSP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHIEUNHAPHANG" ADD CONSTRAINT "PHIEUNHAPHANG_MaNCC_fkey" FOREIGN KEY ("MaNCC") REFERENCES "public"."NHACUNGCAP"("MaNCC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHIEUNHAPHANG" ADD CONSTRAINT "PHIEUNHAPHANG_MaTKNVQL_fkey" FOREIGN KEY ("MaTKNVQL") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PHIEUNHAPHANG" ADD CONSTRAINT "PHIEUNHAPHANG_MaTKNVXN_fkey" FOREIGN KEY ("MaTKNVXN") REFERENCES "public"."TAIKHOAN"("MaTK") ON DELETE SET NULL ON UPDATE CASCADE;
